= Building

[NOTE]
These build instructions assume you have the following installed on your system: (1) link:http://golang.org/doc/install[Go Programming Language] which must be at least version 1.7, (2) link:http://git-scm.com/book/en/v2/Getting-Started-Installing-Git[git], (3) link:https://docs.docker.com/installation/[Docker], and (4) make. To run Hawkular OpenShift Agent inside OpenShift after you build it, it is assumed you have a running OpenShift environment available to you. If you do not, you can find a set of link:#setting-up-openshift[instructions on how to set up OpenShift below].

To build Hawkular OpenShift Agent:

* Clone this repository inside a GOPATH. These instructions will use the example GOPATH of "/source/go/hawkular-openshift-agent" but you can use whatever you want. Just change the first line of the below instructions to use your GOPATH.

[source,shell]
----
export GOPATH=/source/go/hawkular-openshift-agent
mkdir -p $GOPATH
cd $GOPATH
mkdir -p src/github.com/hawkular
cd src/github.com/hawkular
git clone git@github.com:hawkular/hawkular-openshift-agent.git
export PATH=${PATH}:${GOPATH}/bin
----

* Install Glide - a Go dependency management tool that Hawkular OpenShift Agent uses to build itself

[source,shell]
----
cd ${GOPATH}/src/github.com/hawkular/hawkular-openshift-agent
make install_glide
----

* Tell Glide to install the Hawkular OpenShift Agent dependencies

[source,shell]
----
cd ${GOPATH}/src/github.com/hawkular/hawkular-openshift-agent
make install_deps
----

* Build Hawkular OpenShift Agent

[source,shell]
----
cd ${GOPATH}/src/github.com/hawkular/hawkular-openshift-agent
make build
----

* At this point you can run the Hawkular OpenShift Agent tests

[source,shell]
----
cd ${GOPATH}/src/github.com/hawkular/hawkular-openshift-agent
make test
----
